### ISSUE TITLE
Converted into a PySimpleGUI Demo Program....

### ISSUE THREAD

**Issue by PySimpleGUI** [nycynik/ascii-font-processor#3]
Hiya!

You inspired me to take what you provided and do some refactoring, feature additions, etc, with the result being a Demo Program.

This is the start of the comment block at the top of the program, like in the other demo programs:

```python
"""
    Adapted from code originally from this fantastic repository:
    https://github.com/nycynik/ascii-font-processor
    Thank you nycynik for a fantastic headstart
"""    
```

Some of the changes I made include:
* There's a whole new parameter added to Multiline so that one can be created without a scrollbar
* The wrap-length for the figlet is computed based on the width of the Multiline element
* Removed the "show" button. Now the output is generated as the user types
* Made into a single file by removing lots of code

I know you're building something bigger so you need the larger structure of your application.  My demo is 46 lines of code so it's quite a bit less of your code, again because I'm doing so much less and don't have the same kind of bigger future waiting for it.  I've dot a dead-end road... you've got the start of a highway 👍 

![image](https://user-images.githubusercontent.com/46163555/111078787-99e4c180-84cd-11eb-881a-ee6afbffa6e3.png)

You'll find the demo here:
https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_pyfiglet.py

If you would like me to modify the attribution to you in any way, please let me know.  Thank you for the inspiration!

**Comment by PySimpleGUI** [comment]
![tNXPkcYf9v](https://user-images.githubusercontent.com/46163555/111079013-7c642780-84ce-11eb-9cb0-b9576664aa3f.gif)

**Comment by PySimpleGUI** [comment]
![sU7eUqBUBS](https://user-images.githubusercontent.com/46163555/111079228-715dc700-84cf-11eb-969d-ea32ecafb388.gif)

**Comment by nycynik** [comment]
That is some fantastic resizing! Thank you for the tips!!

**Comment by PySimpleGUI** [comment]
Thank you!  (bows)
I'm kinda proud of this one.

You also spurred the addition of a sizable feature, although it's hidden behind the single `scrollbar` parameter.  The Multiline can now be a simple Text widget or it can be a ScrolledText.... hmmmm.... now that I looked at the `Listbox` element, it has a `no_scrollbar` parameter so I'll be changing the multiline quickly over to that parameter name.

Anyway.... point of this is that you made something inspirational and educational.  Good stuff!  Keep doing whatever you're doing.  You've got some awesome results.
